### ISSUE TITLE
Two metrics with the same name (accuracy)

### ISSUE THREAD

**Issue by burakozpoyraz** [hasanabs/B_DNN#1]
When I run "B_DNN_Training" in Colab Notebook, it throws the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a2eacd4086f7> in <module>()
     83 if latest!=None: #If previously there is a trained model with the same configuration will automatically continue the learning process
     84     model.load_weights(latest)
---> 85 model.fit(np.transpose(D),train_labels_app, validation_split=0.25, batch_size=512, epochs=50, callbacks=[callbacks_list, tensorboard], shuffle=True)
     86 
     87 print ("\nTraining time : ", time.time()-start, "seconds.")

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:758 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:387 update_state
        self.build(y_pred, y_true)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:329 build
        self._set_metric_names()
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:349 _set_metric_names
        m._name))

    ValueError: Found two metrics with the same name: Symbol_1_accuracy

**Comment by burakozpoyraz** [comment]
First import accuracy metric,
`from tensorflow.keras.metrics import Accuracy`

Then change following line as given,
`matriks.append("accuracy")` ---> `matriks.append(Accuracy(name="Accuracy" + str(active + 1)))`

This resolved my problem.

**Comment by hasanabs** [comment]
That's because of the newer version of Tensorflow 2.4, you can downgrade to Tensorflow 2.1, or Tensorflow 2.0 as recomendation in my repository to resolve this issue.

Regarding the Tensorflow 2.4 bug, last week I made a report to Tensorflow as you can see here : https://github.com/tensorflow/tensorflow/issues/48690

**Comment by hasanabs** [comment]
That's because of the newer version of Tensorflow 2.4, you can downgrade to Tensorflow 2.1, or Tensorflow 2.0 as recomendation in my repository to resolve this issue.

Regarding the Tensorflow 2.4 bug, last week I made a report to Tensorflow as you can see here : tensorflow/tensorflow#48690

By the way, thank you for your issue. Based on your suggestion, now my program can work on Tensorflow 2.4
