### ISSUE TITLE
Shapes (None, 4) and (None, 1) are incompatible

### ISSUE THREAD

**Issue by burakozpoyraz** [hasanabs/B_DNN#2]
Once the metric issue is resolved, following error is thrown by Colab when I run "B-DNN_Training":

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-606d18b218ea> in <module>()
     39 if latest!=None: #If previously there is a trained model with the same configuration will automatically continue the learning process
     40     model.load_weights(latest)
---> 41 model.fit(np.transpose(D),train_labels_app, validation_split=0.25, batch_size=512, epochs=50, callbacks=[callbacks_list, tensorboard], shuffle=True)
     42 
     43 print ("\nTraining time : ", time.time()-start, "seconds.")

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:758 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:408 update_state
        metric_obj.update_state(y_t, y_p, sample_weight=mask)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/metrics_utils.py:90 decorated
        update_op = update_state_fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/metrics.py:177 update_state_fn
        return ag_update_state(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/metrics.py:618 update_state  **
        matches = ag_fn(y_true, y_pred, **self._fn_kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/metrics.py:3214 accuracy  **
        y_pred.shape.assert_is_compatible_with(y_true.shape)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 4) and (None, 1) are incompatible

**Comment by burakozpoyraz** [comment]
You define output nodes as M; however, you feed only the index of the symbol as output when constructing the training output labels. Therefore, changing training output labels shape to (Ns, M) and loss to categorical_entropy instead of sparse_categorical_entropy resolves the problem.

**Comment by hasanabs** [comment]
> You define output nodes as M; however, you feed only the index of the symbol as output when constructing the training output labels. Therefore, changing training output labels shape to (Ns, M) and loss to categorical_entropy instead of sparse_categorical_entropy resolves the problem.

Thanks for your issue report, first of all because this version is compatible with Tensorflow 2.0, as I mentioned in the repository description. I tried to run  this on Tensorflow 2.4, its incompatible.
I have another solution if you are considering using sparse_categorical_crossentropy because of the simplicity of vector labels. You can change this line in fungsi.py:
loss.append('sparse_categorical_crossentropy'); matriks.append('accuracy')

To this:
loss.append(keras.losses.SparseCategoricalCrossentropy()); matriks.append(keras.metrics.SparseCategoricalAccuracy("accuracy"+str(active+1)))

**Comment by hasanabs** [comment]
Thanks for your problem reporting, first of all because this version is compatible with Tensorflow 2.0, as I mentioned in the repository description. I'm trying to run this on Tensorflow 2.4, it's not compatible.

If you still consider to use TF 2.4, I have another solution if you are considering using sparse_categorical_crossentropy because of the simplicity of vector labels. You can delete the comented code in this picture and add the red area
![Screenshot from 2021-04-30 10-25-33](https://user-images.githubusercontent.com/26079804/116641442-596ad580-a99f-11eb-8ac1-e5a8a866e07a.png)

**Comment by burakozpoyraz** [comment]
Thanks for your feedback, I was also thinking that those problems would be because of version difference. I actually resolved the accuracy metric error, but thanks for another idea. However, I'm still confused about the dimensions of the output layer. As I understand from the paper, the model aims to predict a symbol out of M possible symbols in the constellation for each active transmit antenna. Therefore, you feed M as the Out_node, which makes sense. The thing that I'm confused about is that while you are constructing the training output labels, you actually feed a single element as the label for each active transmit antenna as if Out_node is 1. This single element is the correct index of the transmitted symbol. I think it should be one hot encoded version, where the output label is numpy array with the shape (1, M) having only a single 1 which is the index of the correct transmitted symbol, and the rest is being zero. In this way the Out_node given to the model and the shape of training output label are compatible.

**Comment by hasanabs** [comment]
We have 2 common methods for classification labeling, providing one-hot encode or giving only an integer. For me, I prefer integer labeling, to make it more "human-readable" when we doing debugging.

For your information:
If we put one-hot labels like [1,0,0] , [0,1,0], [0,0,1]. Our loss function should be categorical crosseentropy.
If we put integer labels like 1, 2, 3. Our loss function should be sparse categorical cross-entropy, so our label size is only 1 no matter how many nodes we have at the output.
Ref: https://stats.stackexchange.com/questions/326065/cross-entropy-vs-sparse-cross-entropy-when-to-use-one-over-the-other

I hope this helpful
