### ISSUE TITLE
Could you please provide the B-CNN code ? 

### ISSUE THREAD

**Issue by shudingyun** [hasanabs/B_DNN#4]
It is mentioned in your article that the CNN network is used, but there is no way to reproduce the network in the provided code

**Comment by hasanabs** [comment]
Here is it [GSM_CNN.zip](https://github.com/hasanabs/B_DNN/files/7656145/GSM_CNN.zip)

**Comment by shudingyun** [comment]
Thank you very much for the code, but this code will have this error during training
![image](https://user-images.githubusercontent.com/78725847/144840654-9d101ebd-4743-46a7-85d0-7feac48bc010.png)

**Comment by hasanabs** [comment]
Since this program is still using the old version of the specification, you can follow the environment guidance as in "WITS Lab Commit" version of B-DNN

**Comment by shudingyun** [comment]
Thank you for your reply. I will use the new environment to reproduce the code

**Comment by shudingyun** [comment]
![image](https://user-images.githubusercontent.com/78725847/144879002-99991ada-33ed-4e95-89fb-02621dcdd94c.png)
There is another problem here. This error will be reported during training, saying that there is no attribute

**Comment by hasanabs** [comment]
Please read the code & the instruction carefully 

The answer can be seen in your screenshot. In line 75 it said

**Comment by shudingyun** [comment]
Thank you for taking the time to answer my questions, my problem has been solved, thank you very much for your help

**Comment by hasanabs** [comment]
You're welcome, Dingyun; I just read your email. Hopefully, your research will be going well.

**Comment by shudingyun** [comment]
Hello, I haven't been in touch for a while, is the research going well? I still have a question about your article, how to change the perfect channel to the imperfect channel, can you help me, thank you very much!

**Comment by hasanabs** [comment]
Hi, in that case, you can perform channel estimation first to estimate the channel which is not given (imperfect).

**Comment by shudingyun** [comment]
Is the channel estimation done before this part or modified in the main program?
![image](https://user-images.githubusercontent.com/78725847/154653532-a3dad9ff-ecba-4ced-b439-29ac193a909e.png)

**Comment by shudingyun** [comment]
I'm not very proficient in python, can you provide some help if you can, and I can provide some compensation if needed

**Comment by hasanabs** [comment]
I think before going to the program, it is better for you to understand the mathematical and telecommunication backgrounds first, channel estimation is not like that

**Comment by hasanabs** [comment]
I didn't provide channel estimation in that program, my focus was on perfect CSI case only

**Comment by shudingyun** [comment]
Thanks for your suggestions, i am considering adding LS channel estimation to this system
