### ISSUE TITLE
Some Questions in Training Code

### ISSUE THREAD

**Issue by KkCabin** [hasanabs/B_DNN#5]
Hello, thank you for your outstanding work and open source spirit.
After carefully studying your code, I have a small question.
https://github.com/hasanabs/B_DNN/blob/e81bd1c1096dd6862d5b6e31c8795164183210de/B-DNN_Training.py#L58C1-L59C61
May I ask in the training code, why these two lines are not encoding the data generated in the previous line, like
` x = fn.encode(data[:, send + index_error * Ns], Nt, Np, M, L1, tac, modulation)`

**Comment by hasanabs** [comment]
It encodes the given data's variable (binary) into M-QAM constellation. Try to debug the code.

**Comment by KkCabin** [comment]
Hello, @hasanabs 
Thank you for your prompt reply.
I understand the function of this code, but I think the index of this data is wrong?
Should the original code
```
data[:,send+index_error*Ns]=np.random.randint(2, size=L)

x=fn.encode(data[:,send],Nt,Np,M,L1,tac,modulation)
```
be changed to
```
data[:,send+index_error*Ns]=np.random.randint(2, size=L)

x=fn.encode(data[:,send+index_error*Ns],Nt,Np,M,L1,tac,modulation) 
```
I don't know if I misunderstood, so I need to trouble you again.

**Comment by hasanabs** [comment]
Yes, you are absolutely right. Thanks for the correction.

**Comment by KkCabin** [comment]
Thank you!
